// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLttHlceLTV_pUjeqq4oeqRFkIvDRGU8Q',
    appId: '1:581042203049:web:ad66d58ab70906b9c7bcb8',
    messagingSenderId: '581042203049',
    projectId: 'wasla-app-10a46',
    authDomain: 'wasla-app-10a46.firebaseapp.com',
    storageBucket: 'wasla-app-10a46.firebasestorage.app',
    measurementId: 'G-0WWJ9FSP7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6eADjN4kHUoKHvPSJBkK6wj7B9vVhGbE',
    appId: '1:581042203049:android:19340b413b054761c7bcb8',
    messagingSenderId: '581042203049',
    projectId: 'wasla-app-10a46',
    storageBucket: 'wasla-app-10a46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFGAeKomDRvhpqmW1kk5UcLhQoIiiRVC8',
    appId: '1:581042203049:ios:af96062725c8477fc7bcb8',
    messagingSenderId: '581042203049',
    projectId: 'wasla-app-10a46',
    storageBucket: 'wasla-app-10a46.firebasestorage.app',
    iosBundleId: 'com.example.product0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFGAeKomDRvhpqmW1kk5UcLhQoIiiRVC8',
    appId: '1:581042203049:ios:af96062725c8477fc7bcb8',
    messagingSenderId: '581042203049',
    projectId: 'wasla-app-10a46',
    storageBucket: 'wasla-app-10a46.firebasestorage.app',
    iosBundleId: 'com.example.product0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLttHlceLTV_pUjeqq4oeqRFkIvDRGU8Q',
    appId: '1:581042203049:web:505b8ae25b7d4829c7bcb8',
    messagingSenderId: '581042203049',
    projectId: 'wasla-app-10a46',
    authDomain: 'wasla-app-10a46.firebaseapp.com',
    storageBucket: 'wasla-app-10a46.firebasestorage.app',
    measurementId: 'G-KEL8DH4T54',
  );
}